Rendering fix
MKamil99/Pokedex pull request #13
Opened 2021-05-17 16:36 UTC by MKamil99

Scrolling down the list will result in spotting cards with placeholders - these pokemons has not been rendered yet.

![image](https://user-images.githubusercontent.com/43967269/118524577-96c0b880-b73e-11eb-9d9b-371d7d46a694.png)

2021-05-17 17:24 UTC, Blazevarjo requested changes
I think that this approach  affects poor performance of flatlist. Better way to tweak performance would be to apply Pure Components to pokemon card, cache data and change fetching whole data to smaller batches. We can also think about optimizing images, but first we should focus on developing major functionality, then will be time for optimizing.

2021-05-17 17:24 UTC, Blazevarjo commented on src/components/PokemonCard.js
Should be pure component so any effects or functionality shouldn't appear here

2021-05-17 17:24 UTC, Blazevarjo commented on src/components/PokemonCard.js
>        <TouchableRipple borderless={true} style={styles.touch} onPress={() => onPress()}>
It's better to pass prop with color

2021-05-17 17:24 UTC, Blazevarjo commented on src/screens/main/Home.js
>          id={id}
If statement in render item also reduce performance in list rendering

2021-05-17 17:24 UTC, Blazevarjo commented on src/screens/main/Home.js
>          id={id}
Also 
```
if (loaded==true)
```
should be changed to 
```
if(loaded)
```

2021-05-17 17:24 UTC, Blazevarjo commented on src/contexts/PokemonDataContext.js
> +    // TO DO: refresh item
State should be treated as immutable.

That's cleaner approach
```
pokemons.findIndex((pokemon) => pokemon.id == newPokemonObject.id)
```

2021-05-18 14:10 UTC, RANDOM-V2N5q approved these changes

2021-05-19 11:17 UTC, merged