Add Pokemon general info component
MKamil99/Pokedex pull request #4
Opened 2021-04-27 16:01 UTC by RANDOM-V2N5q

<img src='https://user-images.githubusercontent.com/44544007/116273942-7c6c6e00-a782-11eb-8827-43a2cbab0d97.png' width='300'/>

2021-04-27 16:51 UTC, Blazevarjo requested changes
Looks good

2021-04-27 16:51 UTC, Blazevarjo commented on src/components/PokemonGeneralInfo.js
> +
Better it's just types with array of types

2021-04-27 16:51 UTC, Blazevarjo commented on src/components/PokemonGeneralInfo.js
> +
that's cleaner with array approach
```suggestion

      <View style={styles.typesContainer}>
       types.map((type, index) => <PokemonType key={index} type={type} passedStyle={styles.type}/>)
      </View>

```

2021-04-27 16:51 UTC, Blazevarjo commented on src/components/PokemonType.js
>    );
I think if we want to change text component's style we should also change props to differentiate styles
```
<View style={[styles.container, { backgroundColor: typeColor }, containerStyle]}>
    <Text style={[styles.content, { color: colors.white }, textStyle]}>{type.toUpperCase()}</Text>
</View>
```

2021-04-27 22:56 UTC, MKamil99 requested changes
I agree with @Blazevarjo - try to add array of types instead of two different types.

2021-04-28 08:38 UTC, MKamil99 approved these changes

2021-04-28 09:58 UTC, Blazevarjo approved these changes

2021-04-28 13:49 UTC, merged