Added navigation from main to detail screens
MKamil99/Pokedex pull request #7
Opened 2021-04-29 15:14 UTC by Blazevarjo

- Added navigation from main to detail screens
- Switched bottom navigation to the one supported by react-navigation
- Added context to share pokemon data in the whole app and fetch data only once
- Removed ApiTesting file because it's not needed anymore

2021-04-29 17:04 UTC, MKamil99 requested changes

2021-04-29 17:04 UTC, MKamil99 commented on src/screens/details/General.js
> +    currentPokemon: { color, sprite },
This part results in crashing the application :(

2021-04-29 17:04 UTC, MKamil99 commented on src/screens/main/HomeTabs.js
>  import React, { useState } from 'react';
'UseState' is not used now, so you can delete it

2021-04-29 17:04 UTC, MKamil99 commented on src/screens/main/HomeTabs.js
> +      <Tab.Screen name='heart' component={Favourites} options={{ tabBarIcon: 'information' }} />
The name should be 'Favourites' and the icon should be 'heart'

2021-04-29 22:01 UTC, MKamil99 approved these changes
Good job! :)

2021-04-30 10:47 UTC, RANDOM-V2N5q approved these changes

2021-04-30 13:46 UTC, merged